name: 'lakehouse_rjd_dbt'
version: '1.0.0'
config-version: 2

flags:
  require_certificate_validation: true

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_rjd_dbt:
    example:
      +materialized: view
